update badger & add documentation to readme
o2r-project/o2r-badger pull request #2
Opened 2017-06-02 13:29 UTC by LukasLohoff

- removes /:service from API
- adds installation instructions and api documentation to the readme
- lots of bugs fixed

2017-06-06 09:49 UTC, nuest requested changes

2017-06-06 09:49 UTC, nuest commented on Dockerfile.local
> +FROM node:boron
Please use the version number here, IMHO node version names are not as common as on other platforms, so `node:6`. Could also be the case for non `.local` Dockerfile.

2017-06-06 09:49 UTC, nuest commented on index.js
>  	debug('badger with API version %s waiting for requests on port %s',
Add the version of badger itself to this log statement, cf. o2r-muncher.

2017-06-06 09:49 UTC, nuest commented on README.md
> +- docker
Docker is a product name, so capital "D".

2017-06-06 09:49 UTC, nuest commented on README.md
> +## Remote installation
This also works "locally". Maybe call this "Container-based execution" ?

2017-06-06 09:49 UTC, nuest commented on config/config.js
>  c.fs.base = env.BADGER_BASEPATH || '/tmp/o2r/';
please check if this property is actually used, if not then remove.

2017-06-06 09:49 UTC, nuest commented on controllers/executability/executability.js
> +        res.status(404).send('{"error":"no service for this type found"}');
Should the function not `return` here?

Recommend to switch the condition and subsequently skip the else clause.

2017-06-06 09:49 UTC, nuest commented on controllers/executability/executability.js
> +    let service = config.executable.mainService;
same code as lines 20 ff., check if you can move this to a common function

2017-06-06 09:49 UTC, nuest commented on controllers/license/license.js
> +    //ToDo: Implement multiple services and a fallback when there is no result
same as in `executability.js`, this seems to be reappearing input validation code which should only be written once, if possible.

2017-06-06 09:49 UTC, nuest commented on controllers/license/license.js
>              }
(comment belongs to next line:) `JSON.parse(..)` reads from file system, which is potentially resource intensive. Do this globally once, not during every function call.

2017-06-06 09:49 UTC, nuest commented on controllers/review-status/review-status.js
> +            if (process.toLowerCase().startsWith('blind')) {
Is there a well defined list of values that DOAJ uses? If so, it would be useful to have a link to their docs from here.

2017-06-06 09:49 UTC, nuest commented on README.md
>  # O2R-Badger
No capital letters in o2r abbreviation, please.

2017-06-07 10:53 UTC, LukasLohoff commented on README.md
> +## Remote installation
Yes, but the part now called "local installation" is also container-based. So maybe "Installation via Docker Hub" and "Manual installation"?

Or I just call it "Installation" and list the two/three options available:
- Docker Hub 
- Docker (building the image manually)
- Node.js

2017-06-07 12:19 UTC, LukasLohoff commented on controllers/review-status/review-status.js
> +            if (process.toLowerCase().startsWith('blind')) {
There seems to be no documentation on the different values used. I just found this at https://libraries.io/github/DOAJ/doaj:

```
        "editorial_review" : {
            "process" : "<type of editorial review process>",
            "url" : "<url to info about editorial review process>"
        }
```

2017-06-07 12:24 UTC, nuest commented on README.md
> +## Remote installation
Good idea! Installation with sub-sections seems the best option, go for it.

2017-06-07 12:24 UTC, nuest commented on controllers/review-status/review-status.js
> +            if (process.toLowerCase().startsWith('blind')) {
OK. Thanks for checking.

2017-06-07 14:16 UTC, merged